//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Providers.entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProvidersDataEntities : DbContext
    {
        public ProvidersDataEntities()
            : base("name=ProvidersDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deals> Deals { get; set; }
        public virtual DbSet<DealStatuses> DealStatuses { get; set; }
        public virtual DbSet<DealTypes> DealTypes { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
        public virtual DbSet<Offices> Offices { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<PersonStatuses> PersonStatuses { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProviderRelationship> ProviderRelationship { get; set; }
        public virtual DbSet<Providers> Providers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
