//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Providers.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deals
    {
        public int Deal_id { get; set; }
        public int Deal_status { get; set; }
        public string Deal_name { get; set; }
        public System.DateTime Deal_date { get; set; }
        public int Deal_provider { get; set; }
        public Nullable<int> Deal_contactPerson { get; set; }
        public Nullable<float> Deal_cost { get; set; }
        public int Deal_type { get; set; }
        public Nullable<int> Deal_supervisor { get; set; }
        public Nullable<int> Deal_product { get; set; }
        public int Deal_col { get; set; }
    
        public virtual DealStatuses DealStatuses { get; set; }
        public virtual DealTypes DealTypes { get; set; }
        public virtual Persons Persons { get; set; }
        public virtual Products Products { get; set; }
        public virtual Providers Providers { get; set; }
        public virtual Users Users { get; set; }
    }
}
