//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Providers.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Providers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Providers()
        {
            this.Deals = new HashSet<Deals>();
            this.Persons = new HashSet<Persons>();
        }
    
        public int Provider_id { get; set; }
        public string Provider_name { get; set; }
        public Nullable<int> Provider_office { get; set; }
        public string Provider_subname { get; set; }
        public string Provider_email { get; set; }
        public int Provider_relationshipType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deals> Deals { get; set; }
        public virtual Offices Offices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Persons> Persons { get; set; }
        public virtual ProviderRelationship ProviderRelationship { get; set; }
    }
}
